import type { Metadata } from 'next';
import { Oswald } from 'next/font/google';
import { ChakraProvider } from '@chakra-ui/react';

const oswald = Oswald({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/favicon.png" type="image/gif" />
            </head>
            <body className={oswald.className} id="body">
                <ChakraProvider>{children}</ChakraProvider>
            </body>
        </html>
    );
}
